[package]
name = "rust-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8"
num_cpus = "1.13"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3